POST 127.0.0.1:8585/api/sign-up
Content-Type: application/json

{
  "email": "jar28@gmail.com",
  "password": "qweqwe"
}

####

POST 127.0.0.1:8585/api/word
Content-Type: application/json

{
  "word": "another word3",
  "translate": "другое слово3",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsIkVtYWlsIjoicXdlQGdtYWlsLmNvbSIsImV4cCI6MTY4NzYzODIwM30.dp_0L6f4hje-FG9Y3wFMpVxx7Byw88RmDJ51CbMy_uQ"
}

####

POST 127.0.0.1:8585/api/sign-in
Content-Type: application/json

{
  "email": "qwe@gmail.com",
  "hash_password": "qweqwe"
}

####

POST 127.0.0.1:8585/api/get-words
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsIkVtYWlsIjoicXdlQGdtYWlsLmNvbSIsImV4cCI6MTY4NzYzODIwM30.dp_0L6f4hje-FG9Y3wFMpVxx7Byw88RmDJ51CbMy_uQ"
}

####

POST 127.0.0.1:8585/api/get-words-period
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsIkVtYWlsIjoicXdlQGdtYWlsLmNvbSIsImV4cCI6MTY4NzYzODIwM30.dp_0L6f4hje-FG9Y3wFMpVxx7Byw88RmDJ51CbMy_uQ",
  "created_at": {
    "first_date": "2023-05-08T00:00:01.000Z",
    "second_date": "2023-06-20T23:59:59.000Z"
  }
}

####

POST 127.0.0.1:8585/api/delete
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsIkVtYWlsIjoicXdlQGdtYWlsLmNvbSIsImV4cCI6MTY4MTgxODUzOX0.LhIT66rTxKG_yGQAVDeRQK4TES9oQ2hFtzZJlIhok34",
  "id": 49
}

####

POST 127.0.0.1:8585/api/update
Content-Type: application/json

{
  "word": "update word 1",
  "translate": "обновленное слово 1",
  "id": 1,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsIkVtYWlsIjoicXdlQGdtYWlsLmNvbSIsImV4cCI6MTY4MTgxODUzOX0.LhIT66rTxKG_yGQAVDeRQK4TES9oQ2hFtzZJlIhok34"
}

####

POST 127.0.0.1:8585/api/training
Content-Type: application/json

{
  "words": {
    "words": [
      {
        "id": 215,
        "word": "test1",
        "translate": "тест1"
      },
      {
        "id": 216,
        "word": "test2",
        "translate": "тест2"
      }
    ]
  },
  "answers": {
    "words": [
      {
        "id": 215,
        "word": "test1",
        "translate": "qwe1"
      },
      {
        "id": 216,
        "word": "test2",
        "translate": "qwe2"
      }
    ]
  },
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsIkVtYWlsIjoicXdlQGdtYWlsLmNvbSIsImV4cCI6MTY4NzYzODIwM30.dp_0L6f4hje-FG9Y3wFMpVxx7Byw88RmDJ51CbMy_uQ"
}

####

POST 127.0.0.1:8585/api/get-statistic
Content-Type: application/json

{
  "training_id": 129,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsIkVtYWlsIjoicXdlQGdtYWlsLmNvbSIsImV4cCI6MTY4NzYzODIwM30.dp_0L6f4hje-FG9Y3wFMpVxx7Byw88RmDJ51CbMy_uQ"
}

####

#POST 127.0.0.1:8585/api/get-training
#Content-Type: application/json
#
#{
#  "training_id": 129,
#  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsIkVtYWlsIjoicXdlQGdtYWlsLmNvbSIsImV4cCI6MTY4NzYzODIwM30.dp_0L6f4hje-FG9Y3wFMpVxx7Byw88RmDJ51CbMy_uQ"
#}

####

POST 127.0.0.1:8080/api/statistic
Content-Type: application/json

{
  "training_id": 71,
  "correct_answers": {
    "words": [
      {
        "id": 196,
        "word": "22",
        "translate": "22"
      },
      {
        "id": 195,
        "word": "21",
        "translate": "21"
      },
      {
        "id": 190,
        "word": "20",
        "translate": "20"
      },
      {
        "id": 189,
        "word": "19",
        "translate": "19"
      },
      {
        "id": 188,
        "word": "18",
        "translate": "18"
      }
    ]
  },
  "wrong_answers": {
    "words": [
      {
        "id": 144,
        "word": "test2",
        "translate": "test"
      }
    ]
  },
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsIkVtYWlsIjoicXdlQGdtYWlsLmNvbSIsImV4cCI6MTY4NzYzODIwM30.dp_0L6f4hje-FG9Y3wFMpVxx7Byw88RmDJ51CbMy_uQ"
}
