POST 127.0.0.1:8080/sign-up
Content-Type: application/json

{
  "email": "qwe@gmail.com",
  "password": "qwe"
}

####

POST 127.0.0.1:8080/word
Content-Type: application/json

{
  "word": "test",
  "translate": "test",
  "user_id": 16
}

####

POST 127.0.0.1:8080/sign-in
Content-Type: application/json

{
  "email": "zxc@gmail.com",
  "hash_password": "zxczxc"
}

####

POST 127.0.0.1:8080/get-words
Content-Type: application/json

{
  "user_id": 1121
}

####

POST 127.0.0.1:8080/get-words-period
Content-Type: application/json

{
  "user_id": 16,
  "created_at": {
    "first_date": "2023-03-29T00:00:01.000Z",
    "second_date": "2023-04-06T23:59:59.000Z"
  }
}

####

POST 127.0.0.1:8080/delete
Content-Type: application/json

{
  "word": "test",
  "user_id": 16
}
