// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package word is a generated GoMock package.
package word

import (
	dto "drunklish/internal/service/word/dto"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CheckUserInDB mocks base method.
func (m *MockRepository) CheckUserInDB(userId int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserInDB", userId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserInDB indicates an expected call of CheckUserInDB.
func (mr *MockRepositoryMockRecorder) CheckUserInDB(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserInDB", reflect.TypeOf((*MockRepository)(nil).CheckUserInDB), userId)
}

// Create mocks base method.
func (m *MockRepository) Create(word, translate string, createdAt time.Time, userId int64) (*dto.ResponseFromCreateWord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", word, translate, createdAt, userId)
	ret0, _ := ret[0].(*dto.ResponseFromCreateWord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(word, translate, createdAt, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), word, translate, createdAt, userId)
}

// DeleteWord mocks base method.
func (m *MockRepository) DeleteWord(userId, id int64) (*dto.ResponseFromDeleting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWord", userId, id)
	ret0, _ := ret[0].(*dto.ResponseFromDeleting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWord indicates an expected call of DeleteWord.
func (mr *MockRepositoryMockRecorder) DeleteWord(userId, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWord", reflect.TypeOf((*MockRepository)(nil).DeleteWord), userId, id)
}

// GetWordByCreated mocks base method.
func (m *MockRepository) GetWordByCreated(userId int64, firstDate, secondDate time.Time) (*dto.ResponseWords, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWordByCreated", userId, firstDate, secondDate)
	ret0, _ := ret[0].(*dto.ResponseWords)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWordByCreated indicates an expected call of GetWordByCreated.
func (mr *MockRepositoryMockRecorder) GetWordByCreated(userId, firstDate, secondDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWordByCreated", reflect.TypeOf((*MockRepository)(nil).GetWordByCreated), userId, firstDate, secondDate)
}

// GetWords mocks base method.
func (m *MockRepository) GetWords(userId int64) (*dto.ResponseWords, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWords", userId)
	ret0, _ := ret[0].(*dto.ResponseWords)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWords indicates an expected call of GetWords.
func (mr *MockRepositoryMockRecorder) GetWords(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWords", reflect.TypeOf((*MockRepository)(nil).GetWords), userId)
}

// Update mocks base method.
func (m *MockRepository) Update(word, translate string, id, userId int64) (*dto.ResponseWord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", word, translate, id, userId)
	ret0, _ := ret[0].(*dto.ResponseWord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(word, translate, id, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), word, translate, id, userId)
}
